-- ===========================================
-- Power BI Datenmodell: ITIL Practice Governance & Bebauungsplan (mit Python/SharePoint-Anbindung)
-- ===========================================

-- 1. Tabelle: ITIL_Practice_Catalogue_07052025
-- Quelle: SharePoint-Export via Python (z. B. mit pandas + Office365 REST API)
-- Enthält zentrale Informationen zu Reifegrad, Nutzung, Phase, Blueprint, Prio etc.

-- Berechnete Spalte: Ampel-Reifegrad (farbliche Codierung)
Ampel_Reifegrad = 
SWITCH(TRUE(),
    [Reifegrad_Num] = 0, "Kritisch",
    [Reifegrad_Num] = 1, "Mittel",
    [Reifegrad_Num] >= 2, "Gut",
    BLANK()
)

-- 2. Tabelle: tbl_ITIL_Bebauungsplan_Map
-- Mapping von Practices zur Blueprint-Kategorie (Front Desk / Back Desk / Self Service)
-- Spalten: Practice | Bereich | Phase | Stufe | Blueprint_Kategorie

-- 3. Tabelle: tbl_Phase_Legende
-- Für strukturierte Filter und Farben
-- Spalten: Phase | Farbe

-- 4. Tabelle: tbl_Practice_Kategorie (optional für ITIL 4)
-- General Management / Service Management / Technical Management
-- Spalten: Practice_Kategorie | Beschreibung

-- 5. Beziehungen:
-- ITIL_Practice_Catalogue_07052025[ITIL Practice] 1:* tbl_ITIL_Bebauungsplan_Map[Practice]
-- ITIL_Practice_Catalogue_07052025[Phase]         *:* tbl_Phase_Legende[Phase]
-- ITIL_Practice_Catalogue_07052025[Kategorie]     *:* tbl_Practice_Kategorie[Practice_Kategorie]

-- 6. Measures / KPIs:

KPI_Anzahl_Kritisch = 
CALCULATE(
    COUNTROWS(ITIL_Practice_Catalogue_07052025), 
    ITIL_Practice_Catalogue_07052025[Reifegrad_Num] = 0
)

KPI_Ø_Reifegrad = 
AVERAGE(ITIL_Practice_Catalogue_07052025[Reifegrad_Num])

KPI_Aktive_Hochrelevante = 
CALCULATE(
    COUNTROWS(ITIL_Practice_Catalogue_07052025),
    ITIL_Practice_Catalogue_07052025[Nutzung] = "aktiv",
    ITIL_Practice_Catalogue_07052025[Prio] IN {"A", "B"}
)

KPI_Backdesk_Anteil = 
DIVIDE(
    CALCULATE(
        COUNTROWS(tbl_ITIL_Bebauungsplan_Map), 
        tbl_ITIL_Bebauungsplan_Map[Bereich] = "Back Desk"
    ),
    COUNTROWS(tbl_ITIL_Bebauungsplan_Map)
)

KPI_Ungeplant_Kritisch = 
CALCULATE(
    COUNTROWS(ITIL_Practice_Catalogue_07052025),
    ITIL_Practice_Catalogue_07052025[Nutzung] = "ungeplant",
    ITIL_Practice_Catalogue_07052025[Reifegrad_Num] = 0
)

-- 7. Visuals:
-- Matrix: ITIL Practice × Phase (Ampel-Farbcodierung)
-- KPI-Karten: KPI_Anzahl_Kritisch, KPI_Ø_Reifegrad, KPI_Aktive_Hochrelevante
-- Filter: Nutzung, Prio, Phase, Blueprint_Kategorie, Practice_Kategorie
-- Synoptic Panel: Blueprint-Darstellung (Frontstage vs. Backstage)
-- Optional: Einbindung dynamischer Refresh über Python-Skript (SharePoint → Power BI)
