let
    Quelle = Folder.Files("C:\Users\DeinName\Documents\Reports"),
    Gefiltert = Table.SelectRows(Quelle, each Text.StartsWith([Name], "Liste_Aktuell")),
    Sortiert = Table.Sort(Gefiltert,{{"Date modified", Order.Descending}}),
    ErsteDatei = Table.FirstN(Sortiert,1),
    Inhalt = Table.AddColumn(ErsteDatei, "Custom", each Excel.Workbook([Content])),
    Expandiert = Table.ExpandTableColumn(Inhalt, "Custom", {"Data"}, {"Data"})
in
    Expandiert
